export const PLAYER_SIDES = {
  andarBahar1: {
    andar: "andar",
    bahar: "bahar",
  },
  andarBahar2: {
    andar: "andar",
    bahar: "bahar",
  },
  lucky7B: {
    low: "low",
    high: "high",
    mid: "mid",
    odd: "odd",
    even: "even",
    black: "black",
    red: "red",
  },
  teenPattiT20: {
    playerA: "playerA",
    playerB: "playerB",
  },
  dragonTiger: {
    dragon: "dragon",
    tiger: "tiger",
    D2: "D2",
    D3: "D3",
    DA: "DA",
    D4: "D4",
    D5: "D5",
    D6: "D6",
    D7: "D7",
    D8: "D8",
    D9: "D9",
    D10: "D10",
    DJ: "DJ",
    DQ: "DQ",
    DK: "DK",
    TA: "TA",
    T2: "T2",
    T3: "T3",
    T4: "T4",
    T5: "T5",
    T6: "T6",
    T7: "T7",
    T8: "T8",
    T9: "T9",
    T10: "T10",
    TJ: "TJ",
    TQ: "TQ",
    TK: "TK",
  },
  dragonTigerLion: {
    dragon: "dragon",
    tiger: "tiger",
    lion: "lion",
    DR: "DR",
    DB: "DB",
    DE: "DE",
    DO: "DO",
    TR: "TR",
    TB: "TB",
    TE: "TE",
    TO: "TO",
    LR: "LR",
    LB: "LB",
    LE: "LE",
    LO: "LO",
  },
};
