name: Deploy Frontend (Instance 2)

on:
  push:
    branches:
      - instance-2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/casgampro-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/casgampro-frontend:${{ github.sha }}

      - name: Deploy to VPS Instance 2 (Frontend)
        run: |
          ssh -o StrictHostKeyChecking=no root@88.222.214.174 << 'EOF'
            cd /root/cgp2/
            docker compose pull frontend
            docker compose up -d frontend
          EOF
